## Encoding

**Converting Discrete Categorical Variable to  Discrete Numberiacal Variable**
**There are 2 types of categorical variables**

- 1.Nominal (Ex: Item type)
- 2.Ordinal (Ex: Outlet_Size (Small, Medium, High))

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('homeprices.csv')
df

         town  area    price
0     Chennai  2600  5500000
1     Chennai  3000  5650000
2     Chennai  3200  6100000
3     Chennai  3600  6800000
4   Bangalore  2600  5850000
5   Bangalore  2800  6150000
6   Bangalore  3300  6500000
7   Bangalore  3600  7100000
8   Hyderabad  2600  5750000
9   Hyderabad  2900  6000000
10  Hyderabad  3100  6200000
11  Hyderabad  3600  6950000

## To convert Nominal Categorical into Numeric

1. **get_dummies() using Pandas**

In [3]:
df = pd.get_dummies(df, drop_first=True)
df

    area    price  town_Chennai  town_Hyderabad
0   2600  5500000          True           False
1   3000  5650000          True           False
2   3200  6100000          True           False
3   3600  6800000          True           False
4   2600  5850000         False           False
5   2800  6150000         False           False
6   3300  6500000         False           False
7   3600  7100000         False           False
8   2600  5750000         False            True
9   2900  6000000         False            True
10  3100  6200000         False            True
11  3600  6950000         False            True

### 2. OneHotEncoding Using sklearn

In [8]:
df = pd.read_csv('homeprices.csv')
print(df.head())

## OneHotcoding : We use the OneHotEncoder from sklearn library

from sklearn.preprocessing import OneHotEncoder

## call the function
enc = OneHotEncoder(drop= 'first')

## fit_transform

enc_df = pd.DataFrame(enc.fit_transform(df[['town']]).toarray())
enc_df

        town  area    price
0    Chennai  2600  5500000
1    Chennai  3000  5650000
2    Chennai  3200  6100000
3    Chennai  3600  6800000
4  Bangalore  2600  5850000

      0    1
0   1.0  0.0
1   1.0  0.0
2   1.0  0.0
3   1.0  0.0
4   0.0  0.0
5   0.0  0.0
6   0.0  0.0
7   0.0  0.0
8   0.0  1.0
9   0.0  1.0
10  0.0  1.0
11  0.0  1.0

In [6]:
# merge with main df

df_ohe = pd.concat([df, enc_df],axis='columns')

# drop the original variable

df_ohe.drop('town', axis = 'columns', inplace =True)


df_ohe

    area    price    0    1
0   2600  5500000  1.0  0.0
1   3000  5650000  1.0  0.0
2   3200  6100000  1.0  0.0
3   3600  6800000  1.0  0.0
4   2600  5850000  0.0  0.0
5   2800  6150000  0.0  0.0
6   3300  6500000  0.0  0.0
7   3600  7100000  0.0  0.0
8   2600  5750000  0.0  1.0
9   2900  6000000  0.0  1.0
10  3100  6200000  0.0  1.0
11  3600  6950000  0.0  1.0

## To convert Ordinal Categorical into Numberic 


#### 1. LabelEncoder

- convert to numeric as per alphabetical order

In [9]:
df = pd.read_csv('homeprices.csv')


from sklearn.preprocessing import LabelEncoder

label = LabelEncoder()

df['town'] = label.fit_transform(df.town)
df

    town  area    price
0      1  2600  5500000
1      1  3000  5650000
2      1  3200  6100000
3      1  3600  6800000
4      0  2600  5850000
5      0  2800  6150000
6      0  3300  6500000
7      0  3600  7100000
8      2  2600  5750000
9      2  2900  6000000
10     2  3100  6200000
11     2  3600  6950000

#### 2. OrdinalEncoder
- convert to numeric as per given order (ascending order) in the function

In [10]:
df = pd.read_csv('homeprices.csv')

from sklearn.preprocessing import OrdinalEncoder


oe = OrdinalEncoder(categories=[['Bangalore','Hyderabad','Chennai']])

df.town = oe.fit_transform(df[['town']])
df

    town  area    price
0    2.0  2600  5500000
1    2.0  3000  5650000
2    2.0  3200  6100000
3    2.0  3600  6800000
4    0.0  2600  5850000
5    0.0  2800  6150000
6    0.0  3300  6500000
7    0.0  3600  7100000
8    1.0  2600  5750000
9    1.0  2900  6000000
10   1.0  3100  6200000
11   1.0  3600  6950000

#### 3. map() using pandas

- convert to numeric as per your choice

In [12]:
df = pd.read_csv('homeprices.csv')

df['town'] = df['town'].map({
    'Bangalore':0,
    'Hyderabad':1,
    'Chennai':2
})

df

    town  area    price
0      2  2600  5500000
1      2  3000  5650000
2      2  3200  6100000
3      2  3600  6800000
4      0  2600  5850000
5      0  2800  6150000
6      0  3300  6500000
7      0  3600  7100000
8      1  2600  5750000
9      1  2900  6000000
10     1  3100  6200000
11     1  3600  6950000