In [79]:
import numpy as np
import pandas as pd

In [80]:
df = pd.read_csv('claimants sample.csv')
df.head()

   CASENUM  SEX  INSUR  SEATBELT   AGE    LOSS  ATTORNEY
0        5    0    1.0         0  50.0  34.940         0
1        3    1    0.0         0  18.0   0.891         1
2       66    0    1.0         0   5.0   0.330         1
3       70    1    1.0         1  31.0   0.037         0
4       96    0    1.0         0  30.0     NaN         1

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   CASENUM   10 non-null     int64
 1   SEX       10 non-null     int64
 2   INSUR     8 non-null      float64
 3   SEATBELT  10 non-null     int64
 4   AGE       9 non-null      float64
 5   LOSS      9 non-null      float64
 6   ATTORNEY  10 non-null     int64
dtypes: float64(3), int64(4)
memory usage: 692.0 bytes

## Check for missing values in each column

In [82]:
df.isnull().sum()

CASENUM     0
SEX         0
INSUR       2
SEATBELT    0
AGE         1
LOSS        1
ATTORNEY    0
dtype: int64

## Dealing the Missing Values

#### **1. Remove the rows that contain missing values**

In [83]:
df1 = df.dropna()
df1

   CASENUM  SEX  INSUR  SEATBELT   AGE    LOSS  ATTORNEY
0        5    0    1.0         0  50.0  34.940         0
1        3    1    0.0         0  18.0   0.891         1
2       66    0    1.0         0   5.0   0.330         1
3       70    1    1.0         1  31.0   0.037         0
5       97    1    1.0         0  35.0   0.309         0
8       51    1    1.0         0  60.0   0.874         1

- We should not remove >5% of original data.
- This is usually OK, for very big data sets, and removing a few will not have a big impact on the result.

In [84]:
df.dropna(inplace=True)

#### 2. Replace the nan values
- Mean 
- Median 
- Mode
- fill with some value

- Continous Variables --> CLMAGE, LOSS --> Replace with either Mean or Median for continous data
- Discrete Variables --> CLMINSUR --> Mode is used for discrete data

In [85]:
df = pd.read_csv('claimants sample.csv')

##### 1. fillna() using pandas

In [86]:
mean = df.CASENUM.mean()
mean

np.float64(48.9)

In [87]:
df['INSUR'].fillna(mean, inplace=True)

C:\Users\abhay\AppData\Local\Temp\ipykernel_8468\2448849656.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['INSUR'].fillna(mean, inplace=True)

In [88]:
median = df['LOSS'].median()
df['LOSS'].fillna(df['LOSS'].median(), inplace=True)

C:\Users\abhay\AppData\Local\Temp\ipykernel_8468\2804198635.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['LOSS'].fillna(df['LOSS'].median(), inplace=True)

In [89]:
median = df['AGE'].median()
df['AGE'].fillna(df['AGE'].median(), inplace=True)

C:\Users\abhay\AppData\Local\Temp\ipykernel_8468\3003133184.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['AGE'].fillna(df['AGE'].median(), inplace=True)

In [90]:
mode = df['INSUR'].mode()[0]
df['INSUR'].fillna(mode, inplace=True)

C:\Users\abhay\AppData\Local\Temp\ipykernel_8468\879697651.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['INSUR'].fillna(mode, inplace=True)

In [91]:
df.isnull().sum()

CASENUM     0
SEX         0
INSUR       0
SEATBELT    0
AGE         0
LOSS        0
ATTORNEY    0
dtype: int64

##### 2. Simplemuter using sklearn

In [92]:
df = pd.read_csv('claimants sample.csv')
df

   CASENUM  SEX  INSUR  SEATBELT   AGE    LOSS  ATTORNEY
0        5    0    1.0         0  50.0  34.940         0
1        3    1    0.0         0  18.0   0.891         1
2       66    0    1.0         0   5.0   0.330         1
3       70    1    1.0         1  31.0   0.037         0
4       96    0    1.0         0  30.0     NaN         1
5       97    1    1.0         0  35.0   0.309         0
6       10    0    NaN         0   9.0   3.538         0
7       36    1    NaN         0  34.0   4.881         0
8       51    1    1.0         0  60.0   0.874         1
9       55    1    1.0         0   NaN   0.350         1

In [93]:
from sklearn.impute import SimpleImputer

In [94]:
mean_imputer = SimpleImputer(strategy='mean')
df['LOSS'] = pd.DataFrame(mean_imputer.fit_transform(df[['LOSS']]))

In [95]:
mean_imputer = SimpleImputer(strategy='mean')
df['AGE'] = pd.DataFrame(mean_imputer.fit_transform(df[['AGE']]))

In [96]:
median_impter = SimpleImputer(strategy='median')
df['CASENUM'] = pd.DataFrame(median_impter.fit_transform(df[['CASENUM']]))

In [97]:
median_impter = SimpleImputer(strategy='median')
df['INSUR'] = pd.DataFrame(median_impter.fit_transform(df[['INSUR']]))

In [98]:
mode_imputer = SimpleImputer(strategy='most_frequent')
df['CASENUM'] = pd.DataFrame(mode_imputer.fit_transform(df[['CASENUM']]))

In [99]:
mode_imputer = SimpleImputer(strategy='most_frequent')
df['INSUR'] = pd.DataFrame(mode_imputer.fit_transform(df[['INSUR']]))

In [100]:
df.isnull().sum()

CASENUM     0
SEX         0
INSUR       0
SEATBELT    0
AGE         0
LOSS        0
ATTORNEY    0
dtype: int64