## Pandas Series

1. Create Series using List

In [1]:
import numpy as np
import pandas as pd

l = ['banana', 42]

s = pd.Series(l)
print(s)

0    banana
1        42
dtype: object

In [2]:
s = pd.Series(l, index=['a','b'])
print(s)

a    banana
b        42
dtype: object

**2. Create Series using Array**

In [3]:
a = np.array(l)

s = pd.Series(a, index= ['a', 'b'])
print(s)

a    banana
b        42
dtype: object

**3. Create Series using Dictionary**

In [4]:
d = { 'a': 1, 'b':2, 'c':3}
ser = pd.Series(d)
print(ser)

a    1
b    2
c    3
dtype: int64

In [5]:
d = { 'a': 1, 'b':2, 'c':3}
ser = pd.Series(d, index= ['a','c'])
print(ser)

a    1
c    3
dtype: int64

In [6]:
d = {'col1':[1,2], 'col2':[3,4]}
df = pd.Series(d)
print(df)

col1    [1, 2]
col2    [3, 4]
dtype: object

## Data Frame --> pandas.DataFrame

**1. Create DataFrame using Dictionary**

In [7]:
d = {'col1':[1,2], 'col2':[3,4]}
df = pd.DataFrame(d)
print(df)

   col1  col2
0     1     3
1     2     4

**2. Create DataFrame using Nested List or 2D array**

In [8]:
temperature_df = pd.DataFrame({
    'city':['Mumbai','Delhi','Hyderabad','Banglore'],
    'temperature':[32, 45, 34, 36]
})

print(temperature_df)

        city  temperature
0     Mumbai           32
1      Delhi           45
2  Hyderabad           34
3   Banglore           36

**Attrubutes**

In [9]:
# Displaying the dimensions of the data frame using shape.
temperature_df.shape

(4, 2)

In [10]:
# Displaying the size of the data frame using size.
temperature_df.size

8

In [11]:
# Displaying the name of the coloumns
temperature_df.columns

Index(['city', 'temperature'], dtype='object')

In [12]:
# Displaying the name of the columns using keys() function.
temperature_df.keys()

Index(['city', 'temperature'], dtype='object')

In [13]:
temperature_df.dtypes

city           object
temperature     int64
dtype: object

**Add a column**

In [14]:
# adding column named 'AQI' tp the dataframe.
temperature_df['AQI']= [120, 150, 100, 80]
print(temperature_df)

        city  temperature  AQI
0     Mumbai           32  120
1      Delhi           45  150
2  Hyderabad           34  100
3   Banglore           36   80

**Drop a row**

- Drop (Need to specify that axis = 0 or  'index', axis = 1 or 'columns')

In [15]:
# Deleting row from the data frame.

df = temperature_df.drop(index=[0])
print(df)

        city  temperature  AQI
1      Delhi           45  150
2  Hyderabad           34  100
3   Banglore           36   80

In [16]:
# Deleting multiple rows from the data frame
df= temperature_df.drop(index =[0,1])
df

        city  temperature  AQI
2  Hyderabad           34  100
3   Banglore           36   80

**Drop a column**

- Drop (Need to specify that axis = 0 or 'index', axis = 1 or 'columns')

In [17]:
# Deleting multiple columns from the data frame using drop() function.
df = temperature_df.drop(columns=['AQI', 'city'])
df

   temperature
0           32
1           45
2           34
3           36

In [18]:
# Deleting multiple columns from the data frame using drop function
df = temperature_df.drop('AQI', axis = 1)
df

        city  temperature
0     Mumbai           32
1      Delhi           45
2  Hyderabad           34
3   Banglore           36

In [19]:
temperature_df = temperature_df.drop('AQI', axis = 1)
temperature_df

        city  temperature
0     Mumbai           32
1      Delhi           45
2  Hyderabad           34
3   Banglore           36

In [20]:
temperature_df

        city  temperature
0     Mumbai           32
1      Delhi           45
2  Hyderabad           34
3   Banglore           36

In [21]:
temperature_df.drop('city', inplace=True, axis =1)
temperature_df

   temperature
0           32
1           45
2           34
3           36

In [22]:
temperature_df = pd.DataFrame({
    'city':['Mumbai','Delhi','Hyderabad','Banglore'],
    'temperature':[32, 45, 34, 36]
})

print(temperature_df)

        city  temperature
0     Mumbai           32
1      Delhi           45
2  Hyderabad           34
3   Banglore           36

In [23]:
humidity_df = pd.DataFrame({
    'city':['Mumbai','Hyderabad','Banglore'],
    'humidity':[68, 65, 74]
})

print(humidity_df)

        city  humidity
0     Mumbai        68
1  Hyderabad        65
2   Banglore        74

### Combining Data frames

option 1: **Append**

In [24]:
# Adding rows to the data frame by adding other data frame
df = temperature_df.append(humidity_df)
df

AttributeError: 'DataFrame' object has no attribute 'append'

In [ ]:
# Adding rows to the data frame by adding other data frame
df = pd.concat([temperature_df,humidity_df])
df

        city  temperature  humidity
0     Mumbai         32.0       NaN
1      Delhi         45.0       NaN
2  Hyderabad         34.0       NaN
3   Banglore         36.0       NaN
0     Mumbai          NaN      68.0
1  Hyderabad          NaN      65.0
2   Banglore          NaN      74.0

In [ ]:
# Adding rows to the data frame by adding other data frame
df = pd.concat([temperature_df,humidity_df], axis = 1)
df

        city  temperature       city  humidity
0     Mumbai           32     Mumbai      68.0
1      Delhi           45  Hyderabad      65.0
2  Hyderabad           34   Banglore      74.0
3   Banglore           36        NaN       NaN

In [ ]:
# Inner join
df = pd.merge(temperature_df, humidity_df, on= 'city', how='inner')
df

        city  temperature  humidity
0     Mumbai           32        68
1  Hyderabad           34        65
2   Banglore           36        74

In [ ]:
# Outer join
df = pd.merge(temperature_df, humidity_df, on='city', how='outer')
df

        city  temperature  humidity
0   Banglore           36      74.0
1      Delhi           45       NaN
2  Hyderabad           34      65.0
3     Mumbai           32      68.0

## Import data

In [ ]:
df = pd.read_excel('liver.xlsx')
df

     Age  Gender    TB   DB  Alkphos  Sgpt  Sgot   TP  ALB    AG  LiverPatient
0     65  Female   0.7  0.1      187    16    18  6.8  3.3  0.90             1
1     62    Male  10.9  5.5      699    64   100  7.5  3.2  0.74             1
2     62    Male   7.3  4.1      490    60    68  7.0  3.3  0.89             1
3     58    Male   1.0  0.4      182    14    20  6.8  3.4  1.00             1
4     72    Male   3.9  2.0      195    27    59  7.3  2.4  0.40             1
..   ...     ...   ...  ...      ...   ...   ...  ...  ...   ...           ...
578   60    Male   0.5  0.1      500    20    34  5.9  1.6  0.37             0
579   40    Male   0.6  0.1       98    35    31  6.0  3.2  1.10             1
580   52    Male   0.8  0.2      245    48    49  6.4  3.2  1.00             1
581   31    Male   1.3  0.5      184    29    32  6.8  3.4  1.00             1
582   38    Male   1.0  0.3      216    21    24  7.3  4.4  1.50             0

[583 rows x 11 columns]